background=#0a0f14
foreground=#c5f1ff

color0=#0a0f14
color1=#ff5f5f
color2=#5fff87
color3=#ffd75f
color4=#5fd7ff
color5=#af87ff
color6=#5fffff
color7=#c5f1ff

color8=#6b7c85
color9=#ff6f6f
color10=#6fff9f
color11=#ffe27a
color12=#6fe3ff
color13=#c59fff
color14=#6fffff
color15=#ffffff
